version: '3'
services:
  backend:
    build: ./backend
    images: 931003996958.dkr.ecr.us-east-1.amazonaws.com/e-commerce-api:${APP_IMAGE_TAG:-latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    images: 931003996958.dkr.ecr.us-east-1.amazonaws.com/e-commerce-app:${APP_IMAGE_TAG:-latest
    ports:
      - "80:80"
    depends_on:
      - backend

