version: '3'
services:
  backend:
    build: ./backend
    image: ${ECR_REGISTRY}/e-commerce-api:${APP_IMAGE_TAG}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    image: ${ECR_REGISTRY}/e-commerce-app:${APP_IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - backend

